spring:
  datasource:
    url: jdbc:mysql://localhost/airbnb?useSSL=false
    username: seller
    password:
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      # Show or not log for each sql query
      show-sql: true
      hibernate:
        # Hibernate ddl auto (validate, create, create-drop, update)
        ddl-auto: update
        # Naming strategy
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
